/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Resume_studioRouteImport } from './routes/resume_studio'
import { Route as ResumeStudioRouteImport } from './routes/resume-studio'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as Job_discoveryRouteImport } from './routes/job_discovery'
import { Route as JobDiscoveryRouteImport } from './routes/job-discovery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as Company_researchRouteImport } from './routes/company_research'
import { Route as CompanyResearchRouteImport } from './routes/company-research'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Resume_studioRoute = Resume_studioRouteImport.update({
  id: '/resume_studio',
  path: '/resume_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeStudioRoute = ResumeStudioRouteImport.update({
  id: '/resume-studio',
  path: '/resume-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const Job_discoveryRoute = Job_discoveryRouteImport.update({
  id: '/job_discovery',
  path: '/job_discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDiscoveryRoute = JobDiscoveryRouteImport.update({
  id: '/job-discovery',
  path: '/job-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Company_researchRoute = Company_researchRouteImport.update({
  id: '/company_research',
  path: '/company_research',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyResearchRoute = CompanyResearchRouteImport.update({
  id: '/company-research',
  path: '/company-research',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRoute
  '/company-research': typeof CompanyResearchRoute
  '/company_research': typeof Company_researchRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/job-discovery': typeof JobDiscoveryRoute
  '/job_discovery': typeof Job_discoveryRoute
  '/jobs': typeof JobsRoute
  '/privacy': typeof PrivacyRoute
  '/radar': typeof RadarRoute
  '/resume': typeof ResumeRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/resume_studio': typeof Resume_studioRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRoute
  '/company-research': typeof CompanyResearchRoute
  '/company_research': typeof Company_researchRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/job-discovery': typeof JobDiscoveryRoute
  '/job_discovery': typeof Job_discoveryRoute
  '/jobs': typeof JobsRoute
  '/privacy': typeof PrivacyRoute
  '/radar': typeof RadarRoute
  '/resume': typeof ResumeRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/resume_studio': typeof Resume_studioRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRoute
  '/company-research': typeof CompanyResearchRoute
  '/company_research': typeof Company_researchRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/job-discovery': typeof JobDiscoveryRoute
  '/job_discovery': typeof Job_discoveryRoute
  '/jobs': typeof JobsRoute
  '/privacy': typeof PrivacyRoute
  '/radar': typeof RadarRoute
  '/resume': typeof ResumeRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/resume_studio': typeof Resume_studioRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/companies'
    | '/company-research'
    | '/company_research'
    | '/contact'
    | '/dashboard'
    | '/job-discovery'
    | '/job_discovery'
    | '/jobs'
    | '/privacy'
    | '/radar'
    | '/resume'
    | '/resume-studio'
    | '/resume_studio'
    | '/settings'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/companies'
    | '/company-research'
    | '/company_research'
    | '/contact'
    | '/dashboard'
    | '/job-discovery'
    | '/job_discovery'
    | '/jobs'
    | '/privacy'
    | '/radar'
    | '/resume'
    | '/resume-studio'
    | '/resume_studio'
    | '/settings'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/companies'
    | '/company-research'
    | '/company_research'
    | '/contact'
    | '/dashboard'
    | '/job-discovery'
    | '/job_discovery'
    | '/jobs'
    | '/privacy'
    | '/radar'
    | '/resume'
    | '/resume-studio'
    | '/resume_studio'
    | '/settings'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  CompaniesRoute: typeof CompaniesRoute
  CompanyResearchRoute: typeof CompanyResearchRoute
  Company_researchRoute: typeof Company_researchRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  JobDiscoveryRoute: typeof JobDiscoveryRoute
  Job_discoveryRoute: typeof Job_discoveryRoute
  JobsRoute: typeof JobsRoute
  PrivacyRoute: typeof PrivacyRoute
  RadarRoute: typeof RadarRoute
  ResumeRoute: typeof ResumeRoute
  ResumeStudioRoute: typeof ResumeStudioRoute
  Resume_studioRoute: typeof Resume_studioRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume_studio': {
      id: '/resume_studio'
      path: '/resume_studio'
      fullPath: '/resume_studio'
      preLoaderRoute: typeof Resume_studioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-studio': {
      id: '/resume-studio'
      path: '/resume-studio'
      fullPath: '/resume-studio'
      preLoaderRoute: typeof ResumeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job_discovery': {
      id: '/job_discovery'
      path: '/job_discovery'
      fullPath: '/job_discovery'
      preLoaderRoute: typeof Job_discoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-discovery': {
      id: '/job-discovery'
      path: '/job-discovery'
      fullPath: '/job-discovery'
      preLoaderRoute: typeof JobDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company_research': {
      id: '/company_research'
      path: '/company_research'
      fullPath: '/company_research'
      preLoaderRoute: typeof Company_researchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-research': {
      id: '/company-research'
      path: '/company-research'
      fullPath: '/company-research'
      preLoaderRoute: typeof CompanyResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  CompaniesRoute: CompaniesRoute,
  CompanyResearchRoute: CompanyResearchRoute,
  Company_researchRoute: Company_researchRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  JobDiscoveryRoute: JobDiscoveryRoute,
  Job_discoveryRoute: Job_discoveryRoute,
  JobsRoute: JobsRoute,
  PrivacyRoute: PrivacyRoute,
  RadarRoute: RadarRoute,
  ResumeRoute: ResumeRoute,
  ResumeStudioRoute: ResumeStudioRoute,
  Resume_studioRoute: Resume_studioRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
